FROM microsoft/aspnetcore:1.1.2
ENV ASPNETCORE_URLS=https://*:8080
USER 0
COPY ./obj/Docker/publish app
WORKDIR app
RUN chown -R 1001:0 /app && chmod -R og+rwx /app
EXPOSE 8080
USER 1001
ENTRYPOINT ["dotnet", "dns-api.dll"]